specVersion: 0.2.0
name: nova
version: 1.0.0
description: Nova SubQuery project
repository: https://github.com/nova-wallet/subquery-nova
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x4a12be580bb959937a1c7a61d5cf24428ed67fa571974b4007645d1886e7c89f'
  endpoint: wss://para.subsocial.network
  chaintypes:
    file: './dist/chaintypes.js'

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 307600
    mapping:
      file: ./dist/src/index.js
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward
        - handler: handleRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slash
        - handler: handleSlashed
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slashed
        - handler: handleBonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Bonded
        - handler: handleUnbonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Unbonded
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleAssetTransfer
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Transferred
        - handler: handleCurrencyTransfer
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
        - handler: handleTokenTransfer
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Transfer
        - handler: handleNewEra
          kind: substrate/EventHandler
          filter:
            module: staking
            method: StakingElection
        - handler: handleStakersElected
          kind: substrate/EventHandler
          filter:
            module: staking
            method: StakersElected